 1. Consider the following sensor readings:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
A sensor has an average measurement error of +2°C.
Perform the following without using a for loop:
Add 2°C to every reading using vectorization

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print(corrected_temperature)

[27 30 33 37 40 29 35 42]


Convert all temperatures from Celsius to Fahrenheit

In [3]:
fahrenheit = (temperature * 9 / 5) + 32
print(fahrenheit)

[ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]


Identify all readings greater than 32°C using Boolean indexing.

In [4]:
readings = temperature[temperature > 32]
print(readings)

[35 38 33 40]


Count how many readings exceed 32°C.

In [5]:
count = np.sum(temperature > 32)
print(count)

4


 Explain how vectorization and Boolean indexing can make data processing more efficient
than explicitly iterating through every value.

Vectorization applies an operation to the entire array at once without using a for loop.
Boolean indexing selects elements that satisfy a condition directly.
Both methods are faster and more efficient than explicitly iterating through every value.

2. The following matrix represents the number of daily steps recorded by four users
over three days:

In [6]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print(steps)

[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


Calculate the total steps recorded.

In [7]:
print("Total steps:", np.sum(steps))

Total steps: 84200


Calculate the mean number of steps.

In [8]:
print("Mean steps:", np.mean(steps))

Mean steps: 7016.666666666667


Find the maximum and minimum values.

In [9]:
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))

Maximum: 9500
Minimum: 4500


Calculate the total steps for each day using axis=0.

In [10]:
print("Total steps for each day:", np.sum(steps, axis=0))

Total steps for each day: [26500 27300 30400]


Calculate the total steps for each user using axis=1.

In [11]:
print("Total steps for each user:", np.sum(steps, axis=1))

Total steps for each user: [18300 24500 14400 27000]


Find the user/day position containing the maximum number of steps using argmax()

In [12]:
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum:", position)

Position of maximum: (np.int64(3), np.int64(2))


3. Write a Python program using NumPy to perform the following operations:

In [2]:
original = np.array([1, 2, 3, 4, 5, 6])
print(original)

[1 2 3 4 5 6]


Create a slice containing elements from index 1 to 4 and store it in a variable named subset.

In [13]:
subset = original[1:5]
print(subset)

[2 3 4 5]


 Modify the first element of subset to 999 and display both original and subset.

In [14]:
subset[0] = 999

print("Original:", original)
print("Subset:", subset)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


Create another slice from original, but this time use .copy(). Modify its first element to 500
and display original and the copied array.

In [15]:
copied_array = original[1:5].copy()
copied_array[0] = 500

print("Original:", original)
print("Copied array:", copied_array)

Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]


Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it
into a 3 × 4 matrix.

In [16]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:
• First row
• Last row
• Second column
• Elements from rows 1–2 and columns 2–3

In [17]:
print(matrix[0])

[1 2 3 4]


In [18]:
print(matrix[-1])

[ 9 10 11 12]


In [19]:
print(matrix[:, 1])

[ 2  6 10]


In [20]:
print(matrix[0:2, 1:3])

[[2 3]
 [6 7]]


Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().

In [21]:
flattened = matrix.flatten()
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
raveled = matrix.ravel()
print(raveled)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Modify an element in the array returned by ravel() and observe whether the original array is
affected.

In [23]:
raveled[0] = 100
print("Original matrix:")
print(matrix)
print("Raveled array:")
print(raveled)

Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Raveled array:
[100   2   3   4   5   6   7   8   9  10  11  12]


 Modify an element in the array returned by flatten() and observe whether the original array is
affected.

In [24]:
flattened[1] = 200
print("Original matrix:")
print(matrix)
print("Flattened array:")
print(flattened)

Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened array:
[  1 200   3   4   5   6   7   8   9  10  11  12]


Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [25]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


4. A simple cognitive-assistive system wants to predict a user's assistance score based
on three factors:
• Sleep hours
• Activity level
• Stress level

In [26]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("X:")
print(X)

print("y:")
print(y)

X:
[[ 6 70  3]
 [ 5 50  6]
 [ 8 80  2]
 [ 4 30  8]]
y:
[40 65 30 85]


Display the shape and dimensions of X.

In [27]:
print("Shape:", X.shape)
print("Dimensions:", X.ndim)

Shape: (4, 3)
Dimensions: 2


Calculate: X.T and explain what the transpose represents.

In [28]:
print(X.T)

[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


Calculate the matrix product: X.T @ X

In [29]:
product = X.T @ X
print(product)

[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


Calculate the matrix inverse using: np.linalg.inv() where appropriate.

In [30]:
inverse = np.linalg.inv(X.T @ X)
print(inverse)

[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


Implement the Ordinary Least Squares equation: 𝛽 = (𝑋!𝑋)"#𝑋!𝑦 using NumPy.

In [31]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Coefficients:", beta)

Coefficients: [-0.15921454  0.14083853 10.06302242]


Explain what the resulting coefficients represent in the context of the three user
features.

The first coefficient represents the effect of sleep hours on the assistance score.
The second coefficient represents the effect of activity level on the assistance score.
The third coefficient represents the effect of stress level on the assistance score.

A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to
obtain a predicted assistance score.

In [32]:
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Predicted assistance score: 75.27862544779117
