1. Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

Addition of 2 in all the element

In [2]:
print(arr + 2)

[12 22 32 42 52]


Multiply 3 with all the elements

In [3]:
print(arr * 3)

[ 30  60  90 120 150]


Divide every element by 2

In [4]:
print(arr / 2)

[ 5. 10. 15. 20. 25.]


2. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]

print("Most frequent value:", most_frequent)
print("Indices:", np.where(x == most_frequent)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]

print("Most frequent value:", most_frequent)
print("Indices:", np.where(y == most_frequent)[0])

Most frequent value: 1
Indices: [0 1 2]


3. For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

In [26]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

Access 1st row, 2nd column

In [27]:
print(arr[0, 1])

20


Access 3rd row, 1st column

In [28]:
print(arr[2, 0])

70


4. Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [8]:
# creating the array
Manishika = np.linspace(10, 100, 25)
print(Manishika)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
# dimension
print("Dimensions:", Manishika.ndim)

Dimensions: 1


In [10]:
# shape
print("Shape:", Manishika.shape)

Shape: (25,)


In [11]:
# total element
print("Total elements:", Manishika.size)

Total elements: 25


In [12]:
# data type
print("Data type:", Manishika.dtype)

Data type: float64


In [13]:
# total bytes
print("Total bytes:", Manishika.nbytes)

Total bytes: 200


In [14]:
# transpose
transpose = Manishika.reshape(25, 1)
print(transpose)

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [16]:
# transpose using t
print(Manishika.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [17]:
ucs420_Manishika = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])

print(ucs420_Manishika)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [18]:
# mean
print("Mean:", np.mean(ucs420_Manishika))

Mean: 43.333333333333336


In [19]:
# median
print("Median:", np.median(ucs420_Manishika))

Median: 37.5


In [20]:
# maximum
print("Maximum:", np.max(ucs420_Manishika))

Maximum: 90


In [21]:
# minimum
print("Minimum:", np.min(ucs420_Manishika))

Minimum: 10


In [22]:
# unique elements
print("Unique elements:", np.unique(ucs420_Manishika))

Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [23]:
# reshape
reshaped_ucs420_Manishika = ucs420_Manishika.reshape(4, 3)
print(reshaped_ucs420_Manishika)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [24]:
# resize
resized_ucs420_Manishika = np.resize(ucs420_Manishika, (2, 3))
print(resized_ucs420_Manishika)

[[10 20 30]
 [40 50 60]]
